### ISSUE TITLE
suggestion for adding modified icon/color for buffer + issue

### ISSUE THREAD

**Issue by bassamsdata** [tomiis4/BufferTabs.nvim#4]
I've been using this plugin for a while and have really enjoyed it. I'd like to thank you for this plugin and I have a few suggestions that might enhance the experience:

It would be helpful to have an icon or **color change** (more fancy in my openion) on modified buffers to distinguish them from saved ones, especially when dealing with multiple buffers.

There seems to be an **issue** when saving and restoring sessions as not all buffers are displayed immediately; I often need to use `:bnext` multiple times.

I've also noticed that when using [mini.bufremove](https://github.com/echasnovski/mini.bufremove) to remove buffers, they don't disappear entirely until I execute `:bnext`, though I'm not entirely sure about the technique used in mini.remove so you might ignore this one.

Regarding **padding**, it might be nice to consider a value like `0.5`, as `1` seems too far apart and `0` too close together. While less important , it could improve aesthetics. (I use `0` even-though they overlaps in column view as they look cool :) )
<img width="228" alt="Screen Shot 2023-09-11 at 9 34 57 AM" src="https://github.com/tomiis4/BufferTabs.nvim/assets/105807570/77b782e7-3b1f-4e3e-ac59-1cbc6f25a099">

Thank you once again for this fantastic plugin!

**Comment by tomiis4** [comment]
Hi, than you for you opinion and reporting that bug

- padding
  - I'm sorry, but padding can't work on decimal numbers, because of terminal limitations. Because it's displayed each on new line, so it won't work
- colors
  - in newest commit it should work if you enter hex value or hl group
- buffer update bug
  - I will try to fix it as soon as possible, but I will not be able to be on pc for few days so it will take time. I'll let you know when it will be fixed.
  
Thank you so much.

**Comment by tomiis4** [comment]
should be fixed

**Comment by bassamsdata** [comment]
Thank you for the prompt response. I've noticed that the buffer updates automatically when using the `mini.remove `plugin to close it, which is much appreciated.

Regarding the **color/icon** suggestion, I may not have explained it clearly earlier. My intention is not to change the color of the active buffer (as it's already different), but rather to have a **distinct color** or icon for buffers that have unsaved changes. It's similar to the `dot` in the picture below, which indicates that a buffer has **unsaved changes.** 

<img width="204" alt="Screen Shot 2023-09-13 at 12 15 47 AM" src="https://github.com/tomiis4/BufferTabs.nvim/assets/105807570/8c60588c-72bf-4fc7-bf4d-df03fa6a114c">


really grateful if you could think about adding this enhancement but Please take your time with this, as it's not an urgent matter.

**Comment by tomiis4** [comment]
Ohh, sorry for the misunderstanding. I'll do it as soon as possible, but I'm not at home so I can do it on monday.

**Comment by bassamsdata** [comment]
thank you for adding the feature. it works flawlessly.
